In [2]:
import tkinter as tk
from tkinter import ttk, messagebox

from tkinter import *
import pyodbc
conn = pyodbc.connect('Driver={ODBC Driver 17 for SQL Server};'
                      'Server=DESKTOP-GM27KTS;'
                      'Database=db_project;'
                      'Trusted_Connection=yes;')
cursor = conn.cursor()
cursor.execute('CREATE TABLE  Ecommerce(product_id int ,product_name varchar(10),product_price int,product_shipment_date varchar(50))')

ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]There is already an object named 'Ecommerce' in the database. (2714) (SQLExecDirectW)")

In [3]:
root = Tk()
root.geometry("800x500")
global e1
global e2
global e3
global e4
 
tk.Label(root, text="Ecommerce Store", fg="red", font=(None, 30)).place(x=300, y=5)
 
tk.Label(root, text="Product ID").place(x=10, y=10)
Label(root, text="Product Name").place(x=10, y=40)
Label(root, text="Product Price").place(x=10, y=70)
Label(root, text="Shipment Date").place(x=10, y=100)

         
   
   
  
 

     
 
e1 = Entry(root)
e1.place(x=140, y=10)
 
e2 = Entry(root)
e2.place(x=140, y=40)
 
e3 = Entry(root)
e3.place(x=140, y=70)
 
e4 = Entry(root)
e4.place(x=140, y=100)
def submitact():
     
    E1 = e1.get()
    E2 = e2.get()
    E3 = e3.get()
    E4 = e4.get()
  
    #print(f"The name entered by you is {E1} {E2}")
  
    Add(E1,E2,E3,E4)

def Add(E1,E2,E3,E4):
     print(f"in add {E1} {E2}")
     cursor.execute('INSERT INTO dbo.Ecommerce VALUES (?,?,?,?)',(E1,E2 ,E3,E4))
     #listBox.insert("", "end", values=(E1,E2,E3,E4))
     conn.commit()
        
def submitact2():
     
    E1 = e1.get()
    E2 = e2.get()
    E3 = e3.get()
    E4 = e4.get()
  
    #print(f"The name entered by you is {E1} {E2}")
  
    Update(E1,E2,E3,E4)

def Update(E1,E2,E3,E4):
     #print(f"in updated {E1} {E2}")
     sql='UPDATE Ecommerce SET product_name=(?) , product_price= (?), product_shipment_date= (?) where product_id=(?)'
     val=(E2,E3,E4,E1)
     cursor.execute(sql,val)
    
     #listBox.insert("", "end", values=(E1,E2,E3,E4))
     conn.commit()
      
        
        
def submitact3():
     
    E1 = e1.get()
    E2 = e2.get()
    E3 = e3.get()
    E4 = e4.get()
  
    #print(f"The name entered by you is {E1} {E2}")
  
    Delete(E1,E2,E3,E4)

def Delete(E1,E2,E3,E4):
     print(f"in add {E1} {E2}")
     cursor.execute('delete from Ecommerce where product_id = (?)',(E1))
     #listBox.insert("", "end", values=(E1,E2,E3,E4))
     conn.commit()
       #mycursor.execute("SELECT id,empname,mobile,salary FROM registation")
       

def Deleteall():
   
     cursor.execute('delete from Ecommerce' )
     #listBox.insert("", "end", values=(E1,E2,E3,E4))
     conn.commit()
       #mycursor.execute("SELECT id,empname,mobile,salary FROM registation")

def Show():
    
    listBox.delete(*listBox.get_children())
    
   
    cursor.execute('SELECT product_id,product_name,product_price,product_shipment_date from Ecommerce')
    records = cursor.fetchall()
    print(records)

    for i, (product_id,product_name,product_size,product_shipment_date) in enumerate(records, start=1):
        
        #listBox.delete(*listBox.get_children())
        
        listBox.insert("", "end", values=(product_id,product_name,product_size,product_shipment_date))
        
        
def clear():
      listBox.delete(*listBox.get_children())
    
    
Button(root, text="Add",command = submitact,height=3, width= 13).place(x=30, y=130)
Button(root, text="update",command = submitact2,height=3, width= 13).place(x=140, y=130)
Button(root, text="Delete",command = submitact3,height=3, width= 13).place(x=250, y=130)
Button(root, text="Show",command = Show,height=3, width= 13).place(x=360, y=130)

Button(root, text="Delete all",command = Deleteall,height=3, width= 13).place(x=470, y=130)
Button(root, text="clear screen",command = clear,height=3, width= 13).place(x=580, y=130)


 
 
cols = ('product_id', 'product_name', 'product_price','product_shipment_date')
listBox = ttk.Treeview(root, columns=cols, show='headings' )
 
for col in cols:
    listBox.heading(col, text=col)
    listBox.grid(row=1, column=0, columnspan=2)
    listBox.place(x=10, y=200) 
 


listBox.bind('<Double-Button-1>')
 
root.mainloop()